#!/usr/bin/env python3
"""Generate the /go/ affiliate-redirect block in _redirects from affiliate-links.json.

Single source of truth = affiliate-links.json. Edit that file, run this script,
and the /go/ block is regenerated. Placeholder links point at the clean vendor URL
with NO tracking param (the old ?ref=salesaiguide was fake and earned nothing).
Live links use the real affiliate URL from the JSON.

All non-/go/ rules already in _redirects (directory index redirects, etc.) are
preserved verbatim.

Usage: python3 scripts/build_redirects.py [--check]
  --check : exit non-zero if _redirects is out of sync with the JSON (no write).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LINKS_FILE = ROOT / "affiliate-links.json"
REDIRECTS_FILE = ROOT / "_redirects"

BEGIN = "# BEGIN affiliate links (generated by scripts/build_redirects.py - edit affiliate-links.json, not here)"
END = "# END affiliate links"


def load_links():
    data = json.loads(LINKS_FILE.read_text())
    return data["links"], data.get("aliases", {})


def build_block(links, aliases):
    lines = [BEGIN]
    # Width for alignment
    all_slugs = list(links) + list(aliases)
    pad = max(len(s) for s in all_slugs) + 2
    for slug, meta in links.items():
        tag = "live " if meta.get("status") == "live" else "PLCH"
        lines.append(f"/go/{slug:<{pad}} {meta['url']:<46} 302   # {tag}")
    if aliases:
        lines.append("# slug aliases (hyphenless variants used by some pages)")
        for alias, target in aliases.items():
            url = links[target]["url"]
            lines.append(f"/go/{alias:<{pad}} {url:<46} 302   # -> {target}")
    lines.append(END)
    return lines


def split_existing(text):
    """Return (preserved_lines) = every line that is not a /go/ rule and not inside
    a previously-generated managed block or its legacy comment headers."""
    preserved = []
    in_block = False
    legacy_comments = {
        "# Affiliate redirects",
        "# Sprint 20 tools",
        "# Alternate slug formats (some pages use hyphenless variants)",
        "# Listed tools on hubs",
    }
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == BEGIN:
            in_block = True
            continue
        if stripped == END:
            in_block = False
            continue
        if in_block:
            continue
        if stripped.startswith("/go/"):
            continue
        if stripped in legacy_comments:
            continue
        preserved.append(line)
    # collapse leading/trailing blank lines in preserved
    while preserved and not preserved[0].strip():
        preserved.pop(0)
    while preserved and not preserved[-1].strip():
        preserved.pop()
    return preserved


def render(links, aliases, existing_text):
    block = build_block(links, aliases)
    preserved = split_existing(existing_text)
    out = block + [""] + preserved
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv
    links, aliases = load_links()
    existing = REDIRECTS_FILE.read_text() if REDIRECTS_FILE.exists() else ""
    new_text = render(links, aliases, existing)
    if check:
        if existing != new_text:
            print("OUT OF SYNC: _redirects does not match affiliate-links.json. Run: python3 scripts/build_redirects.py")
            return 1
        print("OK: _redirects is in sync with affiliate-links.json")
        return 0
    REDIRECTS_FILE.write_text(new_text)
    live = sum(1 for m in links.values() if m.get("status") == "live")
    plch = len(links) - live
    print(f"Wrote {REDIRECTS_FILE.name}: {len(links)} tools ({live} live, {plch} placeholder) + {len(aliases)} aliases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
